name: Docker Image Build and Run

on:
  push:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Build Docker Image
      run: docker build -t sentiment-analysis-app ./app
      
    - name: Run Docker Container
      run: docker run -d -p 8080:5000 sentiment-analysis-app
